[package]
name = "file-shover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
env_logger = "0.11"
log = "0.4.27"
rayon = "1.10.0"
